updating the seed. now cards have photos
nguyeners/winnerscapstone pull request #19
Opened 2022-05-02 18:25 UTC by paulazenanguyen

2022-05-02 18:41 UTC, WalkerTexas-coder submitted a review, later dismissed

2022-05-03 17:33 UTC, sjproctor requested changes
Need to removed some comments!

2022-05-03 17:33 UTC, sjproctor commented on app/assets/stylesheets/application.scss
> +// }
Commented out code should be removed from the PR.

2022-05-03 17:33 UTC, sjproctor commented on app/assets/stylesheets/application.scss
> +  // background-attachment: fixed;
Same thing here. Commented out code should not be pushed to main.

2022-05-03 17:33 UTC, sjproctor commented on app/javascript/components/components/Header.js
> +            <NavLink href="/" id='nav-text'>Home</NavLink>
You should be consistent with your quotations. Looks like you are using double quotes for most of your tags.

2022-05-03 17:51 UTC, sjproctor approved these changes

2022-05-03 17:54 UTC, merged